type: object
properties:
  product_id:
    type: string
    description: 製品のユニークID
  name:
    type: string
    description: 製品名
  model_number:
    type: string
    description: 型番
  product_url:
    type: string
    description: 商品のURL
  remarks:
    type: string
    description: 備考欄
required:
  - product_id
  - name
