products:
  get:
    tags:
      - products
    summary: 製品一覧取得
    responses:
      "200":
        description: 製品一覧
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "../schemas/product.yaml"
  post:
    tags:
      - products
    summary: 製品新規登録
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../schemas/product.yaml"
    responses:
      "201":
        description: 製品登録成功
        content:
          application/json:
            schema:
              $ref: "../schemas/product.yaml"
      "400":
        description: 必須項目の入力漏れなど

products-{product_id}:
  get:
    tags:
      - products
    summary: 製品情報取得
    parameters:
      - in: path
        name: product_id
        schema:
          type: string
        required: true
        description: 製品のID
    responses:
      "200":
        description: 製品情報
        content:
          application/json:
            schema:
              $ref: "../schemas/product.yaml"
      "404":
        description: 製品が見つかりません
  put:
    tags:
      - products
    summary: 製品情報更新
    parameters:
      - in: path
        name: product_id
        schema:
          type: string
        required: true
        description: 製品のID
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../schemas/product.yaml"
    responses:
      "200":
        description: 製品情報更新成功
        content:
          application/json:
            schema:
              $ref: "../schemas/product.yaml"
      "400":
        description: 必須項目の入力漏れなど
      "404":
        description: 製品が見つかりません
  delete:
    tags:
      - products
    summary: 製品削除
    parameters:
      - in: path
        name: product_id
        schema:
          type: string
        required: true
        description: 製品のID
    responses:
      "204":
        description: 製品削除成功
      "404":
        description: 製品が見つかりません
