openapi: 3.0.3
info:
  title: KEMOMIMI API
  version: v1
  description: 備品管理システムのREST API仕様書です。

tags:
  - name: public items
    description: 備品
  - name: public items-users
    description: 備品ユーザー
  - name: private items
    description: 私物
  - name: graduation
    description: 卒業関連
  - name: products
    description: 製品
  - name: categories
    description: 分類
  - name: products-categories
    description: 製品分類
  - name: purchase requests
    description: 購入申請
  - name: purchase requests status
    description: 購入申請状態
  - name: users
    description: 部員
  - name: auth
    description: 認証

paths:
  /public_items:
    $ref: "./paths/public_items.yaml#/public_items"
components:
  schemas:
    $ref: "./schemas/index.yaml"
