openapi: 3.0.3
info:
  title: KEMOMIMI API
  version: v1
  description: 備品管理システムのREST API仕様書です。

tags:
  - name: PublicItems
    description: 備品
  - name: PublicItems-MainUser
    description: 備品ユーザー
  - name: PrivateItems
    description: 私物
  - name: PostGradTreat
    description: 卒業後の私物の処理
  - name: Products
    description: 製品
  - name: Categories
    description: 分類
  - name: Products-Categories
    description: 製品分類
  - name: PurchaseRequests
    description: 購入申請
  - name: PurchaseRequestsStatus
    description: 購入申請状態
  - name: Users
    description: 部員
  - name: Auth
    description: 認証

paths:
  /public_items:
    $ref: "./paths/public_items.yaml#/public_items"
  /public_items/{public_item_id}:
    $ref: "./paths/public_items.yaml#/public_items-{public_item_id}"
  /private_items:
    $ref: "./paths/private_items.yaml#/private_items"
  /private_items/{private_item_id}:
    $ref: "./paths/private_items.yaml#/private_items-{private_item_id}"
components:
  schemas:
    $ref: "./schemas/index.yaml"
