openapi: 3.0.3
info:
  title: KEMOMIMI API
  version: v1
  description: 備品管理システムのREST API仕様書です。

paths:
  /users:
    get:
      summary: 部員一覧取得
      responses:
        "200":
          description: 部員一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      summary: 部員新規登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: 部員登録成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: 必須項目の入力漏れなど
  /users/{user_id}:
    get:
      summary: 部員情報取得
      parameters:
        - in: path
          name: user_id
          schema:
            type: string
          required: true
          description: 部員のID
      responses:
        "200":
          description: 部員情報
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: 部員が見つかりません
    put:
      summary: 部員情報更新
      parameters:
        - in: path
          name: user_id
          schema:
            type: string
          required: true
          description: 部員のID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: 部員情報更新成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: 必須項目の入力漏れなど
        "404":
          description: 部員が見つかりません
    delete:
      summary: 部員削除
      parameters:
        - in: path
          name: user_id
          schema:
            type: string
          required: true
          description: 部員のID
      responses:
        "204":
          description: 部員削除成功
        "404":
          description: 部員が見つかりません

  /purchase_requests:
    get:
      summary: 購入申請一覧取得
      responses:
        "200":
          description: 購入申請一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PurchaseRequest"
    post:
      summary: 購入申請新規作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PurchaseRequest"
      responses:
        "201":
          description: 購入申請作成成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseRequest"
        "400":
          description: 必須項目の入力漏れなど

  /purchase_requests/{purchase_request_id}:
    get:
      summary: 購入申請情報取得
      parameters:
        - in: path
          name: purchase_request_id
          schema:
            type: string
          required: true
          description: 購入申請ID
      responses:
        "200":
          description: 購入申請情報
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseRequest"
        "404":
          description: 購入申請が見つかりません
    put:
      summary: 購入申請情報更新
      parameters:
        - in: path
          name: purchase_request_id
          schema:
            type: string
          required: true
          description: 購入申請ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PurchaseRequest"
      responses:
        "200":
          description: 購入申請情報更新成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseRequest"
        "400":
          description: 必須項目の入力漏れなど
        "404":
          description: 購入申請が見つかりません
    delete:
      summary: 購入申請削除
      parameters:
        - in: path
          name: purchase_request_id
          schema:
            type: string
          required: true
          description: 購入申請ID
      responses:
        "204":
          description: 購入申請削除成功
        "404":
          description: 購入申請が見つかりません

  /purchase_request_statuses:
    get:
      summary: 購入申請状態一覧取得
      responses:
        "200":
          description: 購入申請状態一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PurchaseRequestStatus"

components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
          description: ユーザーのユニークID
        handle_name:
          type: string
          description: ユーザーのハンドルネーム
        screen_name:
          type: string
          description: ユーザーのスクリーンネーム
        slack_id:
          type: string
          description: ユーザーのSlack ID
        is_admin:
          type: boolean
          description: 管理者フラグ
        is_member:
          type: boolean
          description: 在籍状況
        graduation_date:
          type: string
          format: date
          description: 卒業日
        remarks:
          type: string
          description: 備考欄
      required:
        - user_id
        - handle_name
        - screen_name

    PurchaseRequest:
      type: object
      properties:
        purchase_request_id:
          type: string
          description: 申請のユニークID
        applicant_id:
          type: string
          description: 申請者のID
        product_id:
          type: string
          description: 申請する製品のID
        cost:
          type: integer
          description: 申請時の想定費用
        status_id:
          type: string
          description: 購入申請状態ID
        request_date:
          type: string
          format: date
          description: 申請作成日
        approval_date:
          type: string
          format: date
          description: 承認日
        remarks:
          type: string
          description: 備考欄
      required:
        - purchase_request_id
        - applicant_id
        - product_id
        - cost
        - status_id

    PurchaseRequestStatus:
      type: object
      properties:
        purchase_request_status_id:
          type: string
          description: 状態のユニークID
        status_name:
          type: string
          description: 状態名
        remarks:
          type: string
          description: 備考欄
      required:
        - purchase_request_status_id
        - status_name
